function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(10)=((1-(1-params(10))*exp((-params(5))))*exp(params(5)))^params(9)/(1-params(9))*((1-(1-params(10))*exp((-params(5))))*exp(params(5)))^(1-params(9))+(1-(1-params(10))*exp((-params(5))))*exp(params(5))*(-params(9))/(1-params(9));
    ys_(11)=((1-(1-params(10))*exp((-params(5))))*exp(params(5)))^params(9)*((1-(1-params(10))*exp((-params(5))))*exp(params(5)))^(-params(9));
    m=params(3)*exp(params(5))^(params(1)-1)*exp(params(5)*(-params(1)));
    k_N=((1/m-(1-params(10)+ys_(10)*params(12))+params(12)*(1-(1-params(10))*exp((-params(5))))*exp(params(5))*ys_(11))/(params(4)*exp(params(5)*(1-params(4)))*(1+ys_(11)*params(12)-params(12))))^(1/(params(4)-1));
    ys_(5)=log(params(11));
    ys_(1)=ys_(5)+log(k_N);
    ys_(4)=params(4)*ys_(1)+(1-params(4))*ys_(5)+params(5)*(-params(4));
    ys_(3)=log((1-(1-params(10))*exp((-params(5))))*exp(ys_(1)));
    ys_(2)=log(exp(ys_(4))-exp(ys_(3)));
    ys_(9)=(exp(ys_(2))-exp((-params(5)))*exp(ys_(2))*params(2))^(-params(1))-params(3)*exp(params(5))^(params(1)-1)*params(2)*(exp(params(5))*exp(ys_(2))-exp(ys_(2))*params(2))^(-params(1));
    r=100*(ys_(10)*params(12)+1+(1+ys_(11)*params(12)-params(12))*exp(ys_(4))*exp(params(5))*params(4)/exp(ys_(1))-params(10)-exp(params(5))*(1-(1-params(10))*exp((-params(5))))*ys_(11)*params(12)-1);
    rf=100*(1/m-1);
    rb=100*(1/m-1);
    Pb=100/rb;
    ys_(12)=0;
    ys_(13)=0;
    ys_(6)=params(5);
    ys_(7)=params(5);
    ys_(8)=params(5);
    N_gr=0;
    rp=0;
    bp=0;
    erp=0;
    ys_(14)=ys_(4)+log(1-params(4))-ys_(5);
    ys_(15)=log(exp(ys_(4))-exp(ys_(14))*exp(ys_(5))-exp(ys_(3)));
    ys_(16)=log(1+r*0.01);
    ys_(17)=log(m);
    Rf=log(m);
    % Auxiliary equations
end
