function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(15)=1-(1-params(13))*exp((-params(6)));
    params(12)=(-params(10))/(1-params(10))*params(15)*exp(params(6));
    params(11)=(params(15)*exp(params(6)))^params(10);
    params(3)=params(4)*exp(params(6))^(params(1)-1);
    ys_(9)=params(12)+params(11)/(1-params(10))*(params(15)*exp(params(6)))^(1-params(10));
    ys_(10)=params(11)*(params(15)*exp(params(6)))^(-params(10));
    m=params(3)*exp(params(6)*(-params(1)));
    k_N=((1/m-(1-params(13)+ys_(9)*params(16))+params(16)*params(15)*exp(params(6))*ys_(10))/(params(5)*exp(params(6)*(1-params(5)))*(1+ys_(10)*params(16)-params(16))))^(1/(params(5)-1));
    N=log(params(14));
    ys_(1)=N+log(k_N);
    ys_(4)=params(5)*ys_(1)+(1-params(5))*N+params(6)*(-params(5));
    ys_(3)=log(params(15)*exp(ys_(1)));
    ys_(2)=log(exp(ys_(4))-exp(ys_(3)));
    ys_(8)=(exp(ys_(2))-exp((-params(6)))*exp(ys_(2))*params(2))^(-params(1))-params(3)*params(2)*(exp(params(6))*exp(ys_(2))-exp(ys_(2))*params(2))^(-params(1));
    r=100*(ys_(9)*params(16)+1+(1+ys_(10)*params(16)-params(16))*exp(ys_(4))*exp(params(6))*params(5)/exp(ys_(1))-params(13)-exp(params(6))*params(15)*ys_(10)*params(16)-1);
    rf=100*(1/m-1);
    rb=100*(1/m-1);
    Pb=100/rb;
    epsilon_a=0;
    ys_(11)=0;
    ys_(5)=params(6);
    ys_(6)=params(6);
    ys_(7)=params(6);
    N_gr=0;
    rp=0;
    bp=0;
    erp=0;
    w=ys_(4)+log(1-params(5))-N;
    d=log(exp(ys_(4))-exp(w)*exp(N)-exp(ys_(3)));
    ys_(12)=log(1+r*0.01);
    ys_(13)=log(m);
    Rf=log(m);
    % Auxiliary equations
end
